### ISSUE TITLE
[H.S.] bouyguestelecom-sms

### ISSUE THREAD

**Issue by kepon85** [cyosp/ids-frontend#1]
Bonjour @cyosp,

Désolé de polluer ce projet pour un autre mais je n'ai pas trouvé comment te contacter autrement. En effet tu as maintenant archivé https://github.com/cyosp/bouyguestelecom-sms c'est à cause de la double authentification par SMS qu'ils ont mis en place (qui du coup fait que ça ne fonctionne plus ton utilitaire) ?
C'était fort pratique pour moi en tout cas... Quoi qu'il en soit merci !

Belle journée,
David

**Comment by cyosp** [comment]
Bonjour David,

Merci pour votre retour et l’enthousiasme autour de [bouyguestelecom-sms](https://github.com/cyosp/bouyguestelecom-sms).
J'ai archivé le repo il y a maintenant plus d'un an car j'ai changé d’opérateur mobile.
Je viens d'enrichir le README du projet de cette information.

Malheureusement je ne vais pas pouvoir faire évoluer [bouyguestelecom-sms](https://github.com/cyosp/bouyguestelecom-sms) pour aborder cette problématique de double authentification.
Peut-être pouvez-vous forker le projet pour aborder le sujet ?

Cordialement,
CYOSP

**Comment by kepon85** [comment]
Merci quand même mais j'ai pas les compétences pour faire évoluer le soft non plus... Tant pi pour moi... Merci quand même,
David
